all:
	(cd tools; make)
	(cd drawBoard; make)
	(cd lineChartDrawer; make)
	(cd mapDrawer; make)
	
clean:
	(cd tools; make clean)
	(cd drawBoard; make clean)
	(cd lineChartDrawer; make clean)
	(cd mapDrawer; make clean)